- name: restart mysql
  service:
    name: mysqld
    state: restarted
- name: restart zabbix-server
  service:
    name: zabbix-server
    state: restarted
- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
- name: restart php
  service:
    name: rh-php72-php-fpm
    state: restarted
- name: restart nginx
  service:
    name: rh-nginx116-nginx
    state: restarted


