- name: Install repo MySQL
  yum:
    name: "{{ mysql_repo }}"
    state: latest
  ignore_errors: True

- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Find MySQL temporary password 
  shell: "grep temporary.*root@localhost /var/log/mysqld.log | sed 's/.*root@localhost: //' | tail -n 1"
  register: mysql_root_password_temp

- name: Debug MySQL temporary password
  debug: 
    msg: "{{ mysql_root_password_temp.stdout }}"

- name: Detect and properly set root password
  stat:
    path: /root/.my.cnf
  register: r

- mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
  when: r.stat.exists==True

- name: Set new password from temporary password
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -uroot -p"{{ mysql_root_password_temp.stdout }}"'
  when: r.stat.exists==False

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  user.root.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
    force: yes

- name: Remove anonymous MySQL user accounts
  mysql_user:
    name: ''
    state: absent

- name: Remove MySQL database test
  mysql_db:
    name: test
    state: absent

- name: Create a new database for Zabbix Server
  mysql_db:
    name: "{{ zbx_database_name }}"
    state: present
    encoding: utf8
    collation: utf8_bin
  tags:
    - zabbix-server

- name: Create Zabbix server MySQL user
  mysql_user:
    name: "{{ zbx_database_name }}"
    password: "{{ zbx_database_password }}"
    priv: "zabbix.*:ALL"
    state: present
  tags:
    - zabbix-server